name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependências
        run: npm install --prefix server

      - name: Instalar a CLI do Heroku
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh

      - name: Deploy para o Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: filipemagalhaessena@gmail.com

      - name: Set environment variables
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
        run: |
          heroku config:set CORS_ORIGINS=${{ secrets.CORS_ORIGINS }} --app ${{ env.HEROKU_APP_NAME }}
          heroku config:set SENDGRID_API_KEY=${{ secrets.SENDGRID_API_KEY }} --app ${{ env.HEROKU_APP_NAME }}
          heroku config:set JWT_SECRET=${{ secrets.JWT_SECRET }} --app ${{ env.HEROKU_APP_NAME }}